# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lint and Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-and-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Easy Zip Files
      uses: papeloto/action-zip@v1
      with:
        files: output/
        dest: build-${{ matrix.node-version }}.zip
        recursive: true # optional, default is true
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ matrix.node-version }}
        # A file, directory or wildcard pattern that describes what to upload
        path: output/build-${{ matrix.node-version }}.zip
